//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyCustomTab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomTab")]
        public string RevitTab {
            get {
                return ((string)(this["RevitTab"]));
            }
            set {
                this["RevitTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("troygates@gmail.com")]
        public string EmailSupport {
            get {
                return ((string)(this["EmailSupport"]));
            }
            set {
                this["EmailSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RevitServerName")]
        public string RevitServerAdmin {
            get {
                return ((string)(this["RevitServerAdmin"]));
            }
            set {
                this["RevitServerAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRevitServerAdmin {
            get {
                return ((bool)(this["ShowRevitServerAdmin"]));
            }
            set {
                this["ShowRevitServerAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yourcompanysintranet/home/etc")]
        public string IntranetAddress {
            get {
                return ((string)(this["IntranetAddress"]));
            }
            set {
                this["IntranetAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.website1.com")]
        public string Website1Address {
            get {
                return ((string)(this["Website1Address"]));
            }
            set {
                this["Website1Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Website 1 Name")]
        public string Website1Name {
            get {
                return ((string)(this["Website1Name"]));
            }
            set {
                this["Website1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.website2.com")]
        public string Website2Address {
            get {
                return ((string)(this["Website2Address"]));
            }
            set {
                this["Website2Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Website 2 Name")]
        public string Website2Name {
            get {
                return ((string)(this["Website2Name"]));
            }
            set {
                this["Website2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.website3.com")]
        public string Website3Address {
            get {
                return ((string)(this["Website3Address"]));
            }
            set {
                this["Website3Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Website 3 Name")]
        public string Website3Name {
            get {
                return ((string)(this["Website3Name"]));
            }
            set {
                this["Website3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Company Intranet")]
        public string IntranetName {
            get {
                return ((string)(this["IntranetName"]));
            }
            set {
                this["IntranetName"] = value;
            }
        }
    }
}
